/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author Apolo
 */
public class FrmAsignacion extends javax.swing.JFrame {

    /**
     * Creates new form FrmAsignacion
     */
    public FrmAsignacion() {
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jplAsignacion = new javax.swing.JPanel();
        lblAsignacion = new javax.swing.JLabel();
        lblAsignacion2 = new javax.swing.JLabel();
        jplAsignacion1 = new javax.swing.JPanel();
        lblAsignacion1 = new javax.swing.JLabel();
        lblAsignacion3 = new javax.swing.JLabel();
        jplAsignacion2 = new javax.swing.JPanel();
        lblAsignacion4 = new javax.swing.JLabel();
        lblAsignacion5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(64, 145, 108));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(149, 213, 178));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jplAsignacion.setBackground(new java.awt.Color(216, 243, 220));
        jplAsignacion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jplAsignacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jplAsignacionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jplAsignacionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jplAsignacionMouseExited(evt);
            }
        });

        lblAsignacion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblAsignacion.setText("UNIDAD");

        lblAsignacion2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblAsignacion2.setText("|");

        javax.swing.GroupLayout jplAsignacionLayout = new javax.swing.GroupLayout(jplAsignacion);
        jplAsignacion.setLayout(jplAsignacionLayout);
        jplAsignacionLayout.setHorizontalGroup(
            jplAsignacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jplAsignacionLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblAsignacion2)
                .addGap(66, 66, 66))
            .addGroup(jplAsignacionLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lblAsignacion)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jplAsignacionLayout.setVerticalGroup(
            jplAsignacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jplAsignacionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAsignacion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblAsignacion2)
                .addContainerGap())
        );

        jPanel2.add(jplAsignacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 100, -1));

        jplAsignacion1.setBackground(new java.awt.Color(216, 243, 220));
        jplAsignacion1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jplAsignacion1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jplAsignacion1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jplAsignacion1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jplAsignacion1MouseExited(evt);
            }
        });

        lblAsignacion1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblAsignacion1.setText("UNIDAD");

        lblAsignacion3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblAsignacion3.setText("||");

        javax.swing.GroupLayout jplAsignacion1Layout = new javax.swing.GroupLayout(jplAsignacion1);
        jplAsignacion1.setLayout(jplAsignacion1Layout);
        jplAsignacion1Layout.setHorizontalGroup(
            jplAsignacion1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jplAsignacion1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblAsignacion3)
                .addGap(62, 62, 62))
            .addGroup(jplAsignacion1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lblAsignacion1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jplAsignacion1Layout.setVerticalGroup(
            jplAsignacion1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jplAsignacion1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblAsignacion1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAsignacion3)
                .addContainerGap())
        );

        jPanel2.add(jplAsignacion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 100, -1));

        jplAsignacion2.setBackground(new java.awt.Color(216, 243, 220));
        jplAsignacion2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jplAsignacion2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jplAsignacion2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jplAsignacion2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jplAsignacion2MouseExited(evt);
            }
        });

        lblAsignacion4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblAsignacion4.setText("UNIDAD");

        lblAsignacion5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblAsignacion5.setText("|||");

        javax.swing.GroupLayout jplAsignacion2Layout = new javax.swing.GroupLayout(jplAsignacion2);
        jplAsignacion2.setLayout(jplAsignacion2Layout);
        jplAsignacion2Layout.setHorizontalGroup(
            jplAsignacion2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jplAsignacion2Layout.createSequentialGroup()
                .addGroup(jplAsignacion2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jplAsignacion2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(lblAsignacion4))
                    .addGroup(jplAsignacion2Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(lblAsignacion5)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jplAsignacion2Layout.setVerticalGroup(
            jplAsignacion2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jplAsignacion2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAsignacion4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAsignacion5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(jplAsignacion2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 100, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, 540));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 930, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 6, 930, 540));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jplAsignacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jplAsignacionMouseClicked
//        isAsignasionesClicked = true;
//
//        JLabel[] labelsBlancos = {lblRevision, lblRevision2};
//        for (JLabel label : labelsBlancos) {
//            label.setForeground(Color.white);
//        }
//
//        JPanel[] panelsCianOscuro = {jplRevision, jplAsignacion};
//        for (JPanel panel : panelsCianOscuro) {
//            panel.setBackground(new Color(0, 204, 204));
//        }
//
//        jplAsignacion.setBackground(Color.WHITE);
//        lblAsignacion.setForeground(Color.blue);
//        lblAsignacion2.setForeground(Color.blue);
//
//        FrmDocente frmDocente = new FrmDocente();
//        JPanel panelDocente = frmDocente.getJPanel1();
//        jPanel5.removeAll();
//        jPanel5.add(panelDocente);
//        jPanel5.revalidate();
//        jPanel5.repaint();
    }//GEN-LAST:event_jplAsignacionMouseClicked

    private void jplAsignacionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jplAsignacionMouseEntered
//        if (!isAsignasionesClicked) {
//            jplAsignacion.setBackground(Color.WHITE);
//            lblAsignacion.setForeground(Color.blue);
//            lblAsignacion2.setForeground(Color.blue);
//        }
    }//GEN-LAST:event_jplAsignacionMouseEntered

    private void jplAsignacionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jplAsignacionMouseExited
//        if (!isAsignasionesClicked) {
//            jplAsignacion.setBackground(new Color(0, 204, 204));
//            lblAsignacion.setForeground(Color.black);
//            lblAsignacion2.setForeground(Color.black);
//        }
    }//GEN-LAST:event_jplAsignacionMouseExited

    private void jplAsignacion1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jplAsignacion1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jplAsignacion1MouseClicked

    private void jplAsignacion1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jplAsignacion1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jplAsignacion1MouseEntered

    private void jplAsignacion1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jplAsignacion1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jplAsignacion1MouseExited

    private void jplAsignacion2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jplAsignacion2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jplAsignacion2MouseClicked

    private void jplAsignacion2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jplAsignacion2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jplAsignacion2MouseEntered

    private void jplAsignacion2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jplAsignacion2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jplAsignacion2MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmAsignacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmAsignacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmAsignacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmAsignacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmAsignacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jplAsignacion;
    private javax.swing.JPanel jplAsignacion1;
    private javax.swing.JPanel jplAsignacion2;
    private javax.swing.JLabel lblAsignacion;
    private javax.swing.JLabel lblAsignacion1;
    private javax.swing.JLabel lblAsignacion2;
    private javax.swing.JLabel lblAsignacion3;
    private javax.swing.JLabel lblAsignacion4;
    private javax.swing.JLabel lblAsignacion5;
    // End of variables declaration//GEN-END:variables
}
