/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author Apolo
 */
public class FrmAsignacion extends javax.swing.JFrame {

    /**
     * Creates new form FrmAsignacion
     */
    public FrmAsignacion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jplAsignacion = new javax.swing.JPanel();
        panelImageAsignacion = new org.edisoncor.gui.panel.PanelImage();
        lblAsignacion = new javax.swing.JLabel();
        lblAsignacion2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 131, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jplAsignacion.setBackground(new java.awt.Color(0, 204, 204));
        jplAsignacion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jplAsignacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jplAsignacionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jplAsignacionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jplAsignacionMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelImageAsignacionLayout = new javax.swing.GroupLayout(panelImageAsignacion);
        panelImageAsignacion.setLayout(panelImageAsignacionLayout);
        panelImageAsignacionLayout.setHorizontalGroup(
            panelImageAsignacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 48, Short.MAX_VALUE)
        );
        panelImageAsignacionLayout.setVerticalGroup(
            panelImageAsignacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        lblAsignacion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblAsignacion.setText("Asignación");

        lblAsignacion2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblAsignacion2.setText("de tareas");

        javax.swing.GroupLayout jplAsignacionLayout = new javax.swing.GroupLayout(jplAsignacion);
        jplAsignacion.setLayout(jplAsignacionLayout);
        jplAsignacionLayout.setHorizontalGroup(
            jplAsignacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jplAsignacionLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(panelImageAsignacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jplAsignacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAsignacion2)
                    .addComponent(lblAsignacion))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jplAsignacionLayout.setVerticalGroup(
            jplAsignacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jplAsignacionLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jplAsignacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelImageAsignacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jplAsignacionLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(lblAsignacion2))
                    .addComponent(lblAsignacion))
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(159, 159, 159)
                .addComponent(jplAsignacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(649, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(276, Short.MAX_VALUE)
                .addComponent(jplAsignacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(241, 241, 241))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jplAsignacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jplAsignacionMouseClicked
//        isAsignasionesClicked = true;
//
//        JLabel[] labelsBlancos = {lblRevision, lblRevision2};
//        for (JLabel label : labelsBlancos) {
//            label.setForeground(Color.white);
//        }
//
//        JPanel[] panelsCianOscuro = {jplRevision, jplAsignacion};
//        for (JPanel panel : panelsCianOscuro) {
//            panel.setBackground(new Color(0, 204, 204));
//        }
//
//        jplAsignacion.setBackground(Color.WHITE);
//        lblAsignacion.setForeground(Color.blue);
//        lblAsignacion2.setForeground(Color.blue);
//
//        FrmDocente frmDocente = new FrmDocente();
//        JPanel panelDocente = frmDocente.getJPanel1();
//        jPanel5.removeAll();
//        jPanel5.add(panelDocente);
//        jPanel5.revalidate();
//        jPanel5.repaint();
    }//GEN-LAST:event_jplAsignacionMouseClicked

    private void jplAsignacionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jplAsignacionMouseEntered
//        if (!isAsignasionesClicked) {
//            jplAsignacion.setBackground(Color.WHITE);
//            lblAsignacion.setForeground(Color.blue);
//            lblAsignacion2.setForeground(Color.blue);
//        }
    }//GEN-LAST:event_jplAsignacionMouseEntered

    private void jplAsignacionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jplAsignacionMouseExited
//        if (!isAsignasionesClicked) {
//            jplAsignacion.setBackground(new Color(0, 204, 204));
//            lblAsignacion.setForeground(Color.black);
//            lblAsignacion2.setForeground(Color.black);
//        }
    }//GEN-LAST:event_jplAsignacionMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmAsignacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmAsignacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmAsignacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmAsignacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmAsignacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jplAsignacion;
    private javax.swing.JLabel lblAsignacion;
    private javax.swing.JLabel lblAsignacion2;
    private org.edisoncor.gui.panel.PanelImage panelImageAsignacion;
    // End of variables declaration//GEN-END:variables
}
