package vista;

import controladores.PeriodoController;
import controlador.TDALista.LinkedList;
import controladores.AsignacionController;
import controladores.CursaController;
import controladores.MateriaControllerListas;
import controladores.PersonaController;
import controladores.TareaController;
import java.awt.Frame;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import modelo.Asignacion;
import modelo.Cursa;
import modelo.Docente;
import modelo.PeriodoAcademico;
import modelo.Persona;
import modelo.Tarea;
import vista.listas.tablas.ModeloTablaAsignacion;
import vista.listas.tablas.ModeloTablaPeriodo;

/**
 *
 * @author alexg
 */
public class FrmInfoCursa extends javax.swing.JDialog {

    ModeloTablaAsignacion mta = new ModeloTablaAsignacion();
    LinkedList<PeriodoAcademico> p = new LinkedList<>();
    private PeriodoController pcl = new PeriodoController();
    private PersonaController perc = new PersonaController();
    private ModeloTablaPeriodo mtp = new ModeloTablaPeriodo();
    private CursaController curc = new CursaController();
    private TareaController tc = new TareaController();
    private AsignacionController asc = new AsignacionController();
    private MateriaControllerListas mac = new MateriaControllerListas();
    private Cursa cursaActual = new Cursa();
    public static JPanel copia;

    /**
     * Creates new form FrmAutos
     */
    public FrmInfoCursa(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        //limpiar();
    }

    public JPanel getJPanel1() {
        return jPanel1;
    }

    public JPanel getPanelAsignaciones() {
        return panelAsignaciones;
    }

    public Cursa getCursaActual() {
        return cursaActual;
    }

    public JTextField getTxtcursa() {
        return txtcursa;
    }

    public JTextField getTxtdocente() {
        return txtdocente;
    }

    public FrmInfoCursa(java.awt.Frame parent, boolean modal, Integer id_cursa) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        cursaActual = curc.obtenerCursaPorID_Cursa(id_cursa);
        //limpiar();
        mostrarDatos();
        //panelAsignaciones.setVisible(false);
        cargarTabla(asc.asignacionesdeCursa(cursaActual.getId()));
    }

    public FrmInfoCursa() {
    }
    
    private void mostrarDatos() {
        if (cursaActual != null) {
            Persona doc = perc.buscar(cursaActual.getId_docente());
            txtmatricula.setText(cursaActual.getId_matricula().toString());
            txtdocente.setText(doc.getNombres()+" "+doc.getApellidos());
            txtcursa.setText(mac.buscarMateria(cursaActual.getId_materia()).toString() + " "+cursaActual.getParalelo());
            //System.out.println("Encontro? el docente: "+doc.getDireccionResidencia());
            //System.out.println("Encontro? el docente: "+doc.getTelefonoCasa());
            //txtdocente.setText(cursaActual.getId_docente().toString());
            //txtcursa.setText(cursaActual.getId().toString());
            //txtmatricula.setText(cursaActual.getId_matricula());
        }
    }

    public void cargarTabla(LinkedList<Asignacion> asignaciones) {
        mta.setAsignaciones(asignaciones);
        tblAsignaciones.setModel(mta);
        tblAsignaciones.updateUI();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtmiembros = new javax.swing.JTextField();
        txtdocente = new javax.swing.JTextField();
        txtcursa = new javax.swing.JTextField();
        txtmatricula = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        panelAsignaciones = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblAsignaciones = new javax.swing.JTable();
        btnabrirasignacion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gestion de Materias");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1140, 642));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Detalles:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        jPanel3.setPreferredSize(new java.awt.Dimension(200, 200));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Curso:");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("Docente encargado:");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setText("Integrantes:");

        txtmiembros.setEditable(false);
        txtmiembros.setText("Periodo Academico ");

        txtdocente.setEditable(false);
        txtdocente.setText("Periodo Academico ");

        txtcursa.setEditable(false);
        txtcursa.setText("Periodo Academico ");

        txtmatricula.setEditable(false);
        txtmatricula.setText("Periodo Academico ");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Matrícula:");

        panelAsignaciones.setBackground(new java.awt.Color(255, 255, 255));
        panelAsignaciones.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Asignaciones de la Unidad:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        tblAsignaciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblAsignaciones);

        btnabrirasignacion.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnabrirasignacion.setText("Abrir asignacion");
        btnabrirasignacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnabrirasignacionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelAsignacionesLayout = new javax.swing.GroupLayout(panelAsignaciones);
        panelAsignaciones.setLayout(panelAsignacionesLayout);
        panelAsignacionesLayout.setHorizontalGroup(
            panelAsignacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAsignacionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 582, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(panelAsignacionesLayout.createSequentialGroup()
                .addGap(244, 244, 244)
                .addComponent(btnabrirasignacion)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelAsignacionesLayout.setVerticalGroup(
            panelAsignacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAsignacionesLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnabrirasignacion)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelAsignaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtmatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtcursa, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtmiembros, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtdocente, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(537, 537, 537))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtmatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcursa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(9, 9, 9)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtdocente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtmiembros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(panelAsignaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(148, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 1140, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 642, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnabrirasignacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnabrirasignacionActionPerformed
        try { 
            int fila = tblAsignaciones.getSelectedRow();
            if (fila > -1) {
                //new FrmSubirEstudiante().setVisible(true);
                Asignacion asigActual = mta.getAsignaciones().get(fila);
                Tarea tActual = tc.buscarTarea(asigActual.getId_tarea());
                //FrmSubirEstudiante asignacion = new FrmSubirEstudiante(asigActual, tActual);
                FrmSubirEstudiante asignacion = new FrmSubirEstudiante((Frame)this.getParent(), asigActual, tActual);
                JPanel panelAsignacion = asignacion.getPrincipalAsignacion();
                copia = jPanel1;
                FrmPrincipalEstudiante1.jplInicio.setEnabled(false);
                FrmPrincipalEstudiante1.jplUnidad1.setEnabled(false);
                FrmPrincipalEstudiante1.jplUnidad2.setEnabled(false);
                FrmPrincipalEstudiante1.jplUnidad3.setEnabled(false);
                jPanel1.removeAll();
                jPanel1.add(panelAsignacion);
                jPanel1.revalidate();
                jPanel1.repaint();
            } else {
                JOptionPane.showMessageDialog(null, "!Seleccione alguna asignación", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
            e.printStackTrace();
            System.out.println("Error al abrir FrmSubirEst: " + e);
            
        }
    }//GEN-LAST:event_btnabrirasignacionActionPerformed

    private void mostrarInfo() {

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmInfoCursa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmInfoCursa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmInfoCursa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmInfoCursa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmInfoCursa dialog = new FrmInfoCursa(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnabrirasignacion;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    public static javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel panelAsignaciones;
    private javax.swing.JTable tblAsignaciones;
    private javax.swing.JTextField txtcursa;
    private javax.swing.JTextField txtdocente;
    private javax.swing.JTextField txtmatricula;
    private javax.swing.JTextField txtmiembros;
    // End of variables declaration//GEN-END:variables
}
