package vista;

import controladores.CuentaControllerListas;
import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author alexg
 */
public class FrmPrincipalAdministrador1 extends javax.swing.JFrame {

    private CuentaControllerListas cc = new CuentaControllerListas();
    private Boolean isDocentesClicked = false;
    private Boolean isEstudiantesClicked = false;
    private Boolean isMateriasClicked = false;
    private Boolean isCursoClicked = false;
    private Boolean isMallaClicked = false;
    private Boolean isMatriculaClicked = false;
    private Boolean isPeriodoAcademicoClicked = false;
    private Boolean isInicioClicked = false;

    /**
     * Creates new form FrmPrincipalAdministrador
     */
    public FrmPrincipalAdministrador1() {
        initComponents();
        this.setLocationRelativeTo(null);
        cargarImagenes();
        jplInicio.setVisible(false);
    }

    private void cargarImagenes() {
        panelImage2.setIcon(new ImageIcon("src/icono/docentes.png"));
        panelImage4.setIcon(new ImageIcon("src/icono/estudiantes.png"));
        panelImage5.setIcon(new ImageIcon("src/icono/materias.png"));
        panelImage7.setIcon(new ImageIcon("src/icono/malla.png"));
        panelImage8.setIcon(new ImageIcon("src/icono/matricula.png"));
        panelImage3.setIcon(new ImageIcon("src/icono/periodoAcademico.png"));
        panelImage9.setIcon(new ImageIcon("src/icono/usuario_prin.png"));
        panelImage11.setIcon(new ImageIcon("src/icono/salir.png"));
        panelImage1.setIcon(new ImageIcon("src/icono/logoEva_1.png"));
        panelImage10.setIcon(new ImageIcon("src/icono/inicio.png"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jplSalir = new javax.swing.JPanel();
        panelImage11 = new org.edisoncor.gui.panel.PanelImage();
        jLabel14 = new javax.swing.JLabel();
        panelImage9 = new org.edisoncor.gui.panel.PanelImage();
        jblNombre = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jplDocentes = new javax.swing.JPanel();
        panelImage2 = new org.edisoncor.gui.panel.PanelImage();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jplEstudiantes = new javax.swing.JPanel();
        panelImage4 = new org.edisoncor.gui.panel.PanelImage();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jplMaterias = new javax.swing.JPanel();
        panelImage5 = new org.edisoncor.gui.panel.PanelImage();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jplMalla = new javax.swing.JPanel();
        panelImage7 = new org.edisoncor.gui.panel.PanelImage();
        jLabel12 = new javax.swing.JLabel();
        jplMatricula = new javax.swing.JPanel();
        panelImage8 = new org.edisoncor.gui.panel.PanelImage();
        jLabel13 = new javax.swing.JLabel();
        jplPeriodoAcademico = new javax.swing.JPanel();
        panelImage3 = new org.edisoncor.gui.panel.PanelImage();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jplInicio = new javax.swing.JPanel();
        panelImage10 = new org.edisoncor.gui.panel.PanelImage();
        jLabel16 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        panelImage1 = new org.edisoncor.gui.panel.PanelImage();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(0, 51, 153));

        jPanel1.setBackground(new java.awt.Color(255, 204, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(255, 255, 255)));

        jplSalir.setBackground(new java.awt.Color(255, 204, 0));
        jplSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jplSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jplSalirMouseClicked(evt);
            }
        });
        jplSalir.setLayout(new java.awt.GridBagLayout());

        javax.swing.GroupLayout panelImage11Layout = new javax.swing.GroupLayout(panelImage11);
        panelImage11.setLayout(panelImage11Layout);
        panelImage11Layout.setHorizontalGroup(
            panelImage11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );
        panelImage11Layout.setVerticalGroup(
            panelImage11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 35;
        gridBagConstraints.ipady = 35;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jplSalir.add(panelImage11, gridBagConstraints);

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setText("Cerrar Sesion");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        jplSalir.add(jLabel14, gridBagConstraints);

        javax.swing.GroupLayout panelImage9Layout = new javax.swing.GroupLayout(panelImage9);
        panelImage9.setLayout(panelImage9Layout);
        panelImage9Layout.setHorizontalGroup(
            panelImage9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        panelImage9Layout.setVerticalGroup(
            panelImage9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jblNombre.setFont(new java.awt.Font("Harlow Solid Italic", 1, 18)); // NOI18N
        jblNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jblNombre.setText("Administrador");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(995, Short.MAX_VALUE)
                .addComponent(panelImage9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jplSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jplSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jblNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)))
                .addGap(0, 6, Short.MAX_VALUE))
            .addComponent(panelImage9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(255, 255, 255)));
        jPanel3.setLayout(new java.awt.GridBagLayout());

        jplDocentes.setBackground(new java.awt.Color(255, 255, 255));
        jplDocentes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jplDocentes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jplDocentesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jplDocentesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jplDocentesMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelImage2Layout = new javax.swing.GroupLayout(panelImage2);
        panelImage2.setLayout(panelImage2Layout);
        panelImage2Layout.setHorizontalGroup(
            panelImage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        panelImage2Layout.setVerticalGroup(
            panelImage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Administrar");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Docentes");

        javax.swing.GroupLayout jplDocentesLayout = new javax.swing.GroupLayout(jplDocentes);
        jplDocentes.setLayout(jplDocentesLayout);
        jplDocentesLayout.setHorizontalGroup(
            jplDocentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jplDocentesLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(panelImage2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jplDocentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)))
        );
        jplDocentesLayout.setVerticalGroup(
            jplDocentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jplDocentesLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jplDocentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelImage2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jplDocentesLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel3))
                    .addComponent(jLabel2)))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 31;
        gridBagConstraints.ipady = 7;
        jPanel3.add(jplDocentes, gridBagConstraints);

        jplEstudiantes.setBackground(new java.awt.Color(255, 255, 255));
        jplEstudiantes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jplEstudiantes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jplEstudiantesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jplEstudiantesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jplEstudiantesMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelImage4Layout = new javax.swing.GroupLayout(panelImage4);
        panelImage4.setLayout(panelImage4Layout);
        panelImage4Layout.setHorizontalGroup(
            panelImage4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        panelImage4Layout.setVerticalGroup(
            panelImage4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Administrar");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Estudiantes");

        javax.swing.GroupLayout jplEstudiantesLayout = new javax.swing.GroupLayout(jplEstudiantes);
        jplEstudiantes.setLayout(jplEstudiantesLayout);
        jplEstudiantesLayout.setHorizontalGroup(
            jplEstudiantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jplEstudiantesLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(panelImage4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jplEstudiantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)))
        );
        jplEstudiantesLayout.setVerticalGroup(
            jplEstudiantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jplEstudiantesLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jplEstudiantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelImage4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jplEstudiantesLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel7))
                    .addComponent(jLabel6)))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 31;
        gridBagConstraints.ipady = 7;
        jPanel3.add(jplEstudiantes, gridBagConstraints);

        jplMaterias.setBackground(new java.awt.Color(255, 255, 255));
        jplMaterias.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jplMaterias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jplMateriasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jplMateriasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jplMateriasMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelImage5Layout = new javax.swing.GroupLayout(panelImage5);
        panelImage5.setLayout(panelImage5Layout);
        panelImage5Layout.setHorizontalGroup(
            panelImage5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        panelImage5Layout.setVerticalGroup(
            panelImage5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Administrar");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Materias");

        javax.swing.GroupLayout jplMateriasLayout = new javax.swing.GroupLayout(jplMaterias);
        jplMaterias.setLayout(jplMateriasLayout);
        jplMateriasLayout.setHorizontalGroup(
            jplMateriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jplMateriasLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(panelImage5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jplMateriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)))
        );
        jplMateriasLayout.setVerticalGroup(
            jplMateriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jplMateriasLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jplMateriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelImage5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addGroup(jplMateriasLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel9))))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipadx = 31;
        gridBagConstraints.ipady = 7;
        jPanel3.add(jplMaterias, gridBagConstraints);

        jplMalla.setBackground(new java.awt.Color(255, 255, 255));
        jplMalla.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jplMalla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jplMallaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jplMallaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jplMallaMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelImage7Layout = new javax.swing.GroupLayout(panelImage7);
        panelImage7.setLayout(panelImage7Layout);
        panelImage7Layout.setHorizontalGroup(
            panelImage7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        panelImage7Layout.setVerticalGroup(
            panelImage7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("Malla");

        javax.swing.GroupLayout jplMallaLayout = new javax.swing.GroupLayout(jplMalla);
        jplMalla.setLayout(jplMallaLayout);
        jplMallaLayout.setHorizontalGroup(
            jplMallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jplMallaLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(panelImage7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jplMallaLayout.setVerticalGroup(
            jplMallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jplMallaLayout.createSequentialGroup()
                .addGroup(jplMallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jplMallaLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel12))
                    .addGroup(jplMallaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panelImage7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.ipadx = 60;
        gridBagConstraints.ipady = -6;
        jPanel3.add(jplMalla, gridBagConstraints);

        jplMatricula.setBackground(new java.awt.Color(255, 255, 255));
        jplMatricula.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jplMatricula.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jplMatriculaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jplMatriculaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jplMatriculaMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelImage8Layout = new javax.swing.GroupLayout(panelImage8);
        panelImage8.setLayout(panelImage8Layout);
        panelImage8Layout.setHorizontalGroup(
            panelImage8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        panelImage8Layout.setVerticalGroup(
            panelImage8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setText("Matricula");

        javax.swing.GroupLayout jplMatriculaLayout = new javax.swing.GroupLayout(jplMatricula);
        jplMatricula.setLayout(jplMatriculaLayout);
        jplMatriculaLayout.setHorizontalGroup(
            jplMatriculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jplMatriculaLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(panelImage8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel13)
                .addContainerGap())
        );
        jplMatriculaLayout.setVerticalGroup(
            jplMatriculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jplMatriculaLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel13)
                .addGap(15, 15, 15))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jplMatriculaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelImage8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.ipadx = 40;
        jPanel3.add(jplMatricula, gridBagConstraints);

        jplPeriodoAcademico.setBackground(new java.awt.Color(255, 255, 255));
        jplPeriodoAcademico.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jplPeriodoAcademico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jplPeriodoAcademicoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jplPeriodoAcademicoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jplPeriodoAcademicoMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelImage3Layout = new javax.swing.GroupLayout(panelImage3);
        panelImage3.setLayout(panelImage3Layout);
        panelImage3Layout.setHorizontalGroup(
            panelImage3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        panelImage3Layout.setVerticalGroup(
            panelImage3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Periodo");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Academico");

        javax.swing.GroupLayout jplPeriodoAcademicoLayout = new javax.swing.GroupLayout(jplPeriodoAcademico);
        jplPeriodoAcademico.setLayout(jplPeriodoAcademicoLayout);
        jplPeriodoAcademicoLayout.setHorizontalGroup(
            jplPeriodoAcademicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jplPeriodoAcademicoLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(panelImage3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jplPeriodoAcademicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)))
        );
        jplPeriodoAcademicoLayout.setVerticalGroup(
            jplPeriodoAcademicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jplPeriodoAcademicoLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jplPeriodoAcademicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelImage3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jplPeriodoAcademicoLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel5))
                    .addComponent(jLabel4)))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.ipadx = 34;
        gridBagConstraints.ipady = 7;
        jPanel3.add(jplPeriodoAcademico, gridBagConstraints);

        jplInicio.setBackground(new java.awt.Color(255, 255, 255));
        jplInicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jplInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jplInicioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jplInicioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jplInicioMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelImage10Layout = new javax.swing.GroupLayout(panelImage10);
        panelImage10.setLayout(panelImage10Layout);
        panelImage10Layout.setHorizontalGroup(
            panelImage10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        panelImage10Layout.setVerticalGroup(
            panelImage10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setText("Inicio");

        javax.swing.GroupLayout jplInicioLayout = new javax.swing.GroupLayout(jplInicio);
        jplInicio.setLayout(jplInicioLayout);
        jplInicioLayout.setHorizontalGroup(
            jplInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jplInicioLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(panelImage10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jplInicioLayout.setVerticalGroup(
            jplInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jplInicioLayout.createSequentialGroup()
                .addGroup(jplInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jplInicioLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel16))
                    .addGroup(jplInicioLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panelImage10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 60;
        gridBagConstraints.ipady = -6;
        jPanel3.add(jplInicio, gridBagConstraints);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setPreferredSize(new java.awt.Dimension(1140, 642));
        jPanel5.setRequestFocusEnabled(false);
        jPanel5.setLayout(new java.awt.GridBagLayout());

        javax.swing.GroupLayout panelImage1Layout = new javax.swing.GroupLayout(panelImage1);
        panelImage1.setLayout(panelImage1Layout);
        panelImage1Layout.setHorizontalGroup(
            panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 595, Short.MAX_VALUE)
        );
        panelImage1Layout.setVerticalGroup(
            panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 592, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 595;
        gridBagConstraints.ipady = 592;
        gridBagConstraints.insets = new java.awt.Insets(50, 50, 50, 50);
        jPanel5.add(panelImage1, gridBagConstraints);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(225, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(67, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 642, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jplDocentesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jplDocentesMouseClicked
        isDocentesClicked = true;
        jplInicio.setVisible(true);

        JLabel[] labelsBlancos = {jLabel6, jLabel7, jLabel8, jLabel9, jLabel16, jLabel12, jLabel13, jLabel4, jLabel5};
        for (JLabel label : labelsBlancos) {
            label.setForeground(Color.black);
        }

        JPanel[] panelsCianOscuro = {jplEstudiantes, jplMaterias, jplMalla, jplInicio, jplMatricula, jplPeriodoAcademico};
        for (JPanel panel : panelsCianOscuro) {
            panel.setBackground(Color.WHITE);
        }

        jplDocentes.setBackground(new Color(255,204,0));
        jLabel2.setForeground(Color.black);
        jLabel3.setForeground(Color.black);

        FrmDocente frmDocente = new FrmDocente();
        JPanel panelDocente = frmDocente.getJPanel1();
        jPanel5.removeAll();
        jPanel5.add(panelDocente);
        jPanel5.revalidate();
        jPanel5.repaint();
    }//GEN-LAST:event_jplDocentesMouseClicked

    private void jplEstudiantesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jplEstudiantesMouseClicked
        isEstudiantesClicked = true;
        jplInicio.setVisible(true);

        JLabel[] labelsBlancos = {jLabel2, jLabel3, jLabel8, jLabel9, jLabel16, jLabel12, jLabel13, jLabel4, jLabel5};
        for (JLabel label : labelsBlancos) {
            label.setForeground(Color.black);
        }

        JPanel[] panelsCianOscuro = {jplDocentes, jplMaterias, jplMalla, jplInicio, jplMatricula, jplPeriodoAcademico};
        for (JPanel panel : panelsCianOscuro) {
            panel.setBackground(Color.WHITE);
        }

        jplEstudiantes.setBackground(new Color(255,204,0));
        jLabel6.setForeground(Color.black);
        jLabel7.setForeground(Color.black);

        FrmEstudiante frmEstudiante = new FrmEstudiante();
        JPanel panelDocente = frmEstudiante.getJPanel1();
        jPanel5.removeAll();
        jPanel5.add(panelDocente);
        jPanel5.revalidate();
        jPanel5.repaint();
    }//GEN-LAST:event_jplEstudiantesMouseClicked

    private void jplMateriasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jplMateriasMouseClicked
        isMateriasClicked = true;
        jplInicio.setVisible(true);

        JLabel[] labelsBlancos = {jLabel2, jLabel3, jLabel6, jLabel7, jLabel16, jLabel12, jLabel13, jLabel4, jLabel5};
        for (JLabel label : labelsBlancos) {
            label.setForeground(Color.black);
        }

        JPanel[] panelsCianOscuro = {jplDocentes, jplEstudiantes, jplMalla, jplInicio, jplMatricula, jplPeriodoAcademico};
        for (JPanel panel : panelsCianOscuro) {
            panel.setBackground(Color.WHITE);
        }

        jplMaterias.setBackground(new Color(255,204,0));
        jLabel8.setForeground(Color.black);
        jLabel9.setForeground(Color.black);

        FrmMateria frmMateria = new FrmMateria();
        JPanel panelMateria = frmMateria.getJPanel1();
        jPanel5.removeAll();
        jPanel5.add(panelMateria);
        jPanel5.revalidate();
        jPanel5.repaint();
    }//GEN-LAST:event_jplMateriasMouseClicked

    private void jplMallaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jplMallaMouseClicked
        isMallaClicked = true;
        jplInicio.setVisible(true);

        JLabel[] labelsBlancos = {jLabel2, jLabel3, jLabel6, jLabel7, jLabel8, jLabel9, jLabel16, jLabel13, jLabel4, jLabel5};
        for (JLabel label : labelsBlancos) {
            label.setForeground(Color.black);
        }

        JPanel[] panelsCianOscuro = {jplDocentes, jplEstudiantes, jplMaterias, jplInicio, jplMatricula, jplPeriodoAcademico};
        for (JPanel panel : panelsCianOscuro) {
            panel.setBackground(Color.WHITE);
        }

        jplMalla.setBackground(new Color(255,204,0));
        jLabel12.setForeground(Color.black);

        FrmMalla frmMalla = new FrmMalla();
        JPanel panelMalla = frmMalla.getJPanel1();
        jPanel5.removeAll();
        jPanel5.add(panelMalla);
        jPanel5.revalidate();
        jPanel5.repaint();
    }//GEN-LAST:event_jplMallaMouseClicked

    private void jplMatriculaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jplMatriculaMouseClicked
        isMatriculaClicked = true;
        jplInicio.setVisible(true);

        JLabel[] labelsBlancos = {jLabel2, jLabel3, jLabel6, jLabel7, jLabel8, jLabel9, jLabel16, jLabel12, jLabel4, jLabel5};
        for (JLabel label : labelsBlancos) {
            label.setForeground(Color.black);
        }

        JPanel[] panelsCianOscuro = {jplDocentes, jplEstudiantes, jplMaterias, jplInicio, jplMalla, jplPeriodoAcademico};
        for (JPanel panel : panelsCianOscuro) {
            panel.setBackground(Color.WHITE);
        }

        jplMatricula.setBackground(new Color(255,204,0));
        jLabel13.setForeground(Color.black);

        FrmMatricula frmMatricula = new FrmMatricula();
        JPanel panelDocente = frmMatricula.getJPanel1();
        jPanel5.removeAll();
        jPanel5.add(panelDocente);
        jPanel5.revalidate();
        jPanel5.repaint();
    }//GEN-LAST:event_jplMatriculaMouseClicked

    private void jplPeriodoAcademicoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jplPeriodoAcademicoMouseClicked
        isPeriodoAcademicoClicked = true;
        jplInicio.setVisible(true);

        JLabel[] labelsBlancos = {jLabel2, jLabel3, jLabel6, jLabel7, jLabel8, jLabel9, jLabel16, jLabel12, jLabel13};
        for (JLabel label : labelsBlancos) {
            label.setForeground(Color.black);
        }

        JPanel[] panelsCianOscuro = {jplDocentes, jplEstudiantes, jplMaterias, jplInicio, jplMalla, jplMatricula};
        for (JPanel panel : panelsCianOscuro) {
            panel.setBackground(Color.WHITE);
        }

        jplPeriodoAcademico.setBackground(new Color(255,204,0));
        jLabel4.setForeground(Color.black);
        jLabel5.setForeground(Color.black);

        FrmPeriodoAcademico frmPeriodo = new FrmPeriodoAcademico(null, true);
        JPanel panelDocente = frmPeriodo.getJPanel1();
        jPanel5.removeAll();
        jPanel5.add(panelDocente);
        jPanel5.revalidate();
        jPanel5.repaint();
    }//GEN-LAST:event_jplPeriodoAcademicoMouseClicked

    private void jplSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jplSalirMouseClicked
        new FrmIniciarSesion().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jplSalirMouseClicked

    private void jplDocentesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jplDocentesMouseEntered
        if (!isDocentesClicked) {
            jplDocentes.setBackground(new Color(255,204,0));
            jLabel2.setForeground(Color.black);
            jLabel3.setForeground(Color.black);
        }
    }//GEN-LAST:event_jplDocentesMouseEntered

    private void jplDocentesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jplDocentesMouseExited
        if (!isDocentesClicked) {
            jplDocentes.setBackground(Color.WHITE);
            jLabel2.setForeground(Color.black);
            jLabel3.setForeground(Color.black);
        }
    }//GEN-LAST:event_jplDocentesMouseExited

    private void jplEstudiantesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jplEstudiantesMouseEntered
        if (!isEstudiantesClicked) {
            jplEstudiantes.setBackground(new Color(255,204,0));
            jLabel6.setForeground(Color.black);
            jLabel7.setForeground(Color.black);
        }
    }//GEN-LAST:event_jplEstudiantesMouseEntered

    private void jplEstudiantesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jplEstudiantesMouseExited
        if (!isEstudiantesClicked) {
            jplEstudiantes.setBackground(Color.WHITE);
            jLabel6.setForeground(Color.black);
            jLabel7.setForeground(Color.black);
        }
    }//GEN-LAST:event_jplEstudiantesMouseExited

    private void jplMateriasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jplMateriasMouseEntered
        if (!isMateriasClicked) {
            jplMaterias.setBackground(new Color(255,204,0));
            jLabel8.setForeground(Color.black);
            jLabel9.setForeground(Color.black);
        }
    }//GEN-LAST:event_jplMateriasMouseEntered

    private void jplMateriasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jplMateriasMouseExited
        if (!isMateriasClicked) {
            jplMaterias.setBackground(Color.WHITE);
            jLabel8.setForeground(Color.black);
            jLabel9.setForeground(Color.black);
        }
    }//GEN-LAST:event_jplMateriasMouseExited

    private void jplMallaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jplMallaMouseEntered
        if (!isMallaClicked) {
            jplMalla.setBackground(new Color(255,204,0));
            jLabel12.setForeground(Color.black);
        }
    }//GEN-LAST:event_jplMallaMouseEntered

    private void jplMallaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jplMallaMouseExited
        if (!isMallaClicked) {
            jplMalla.setBackground(Color.WHITE);
            jLabel12.setForeground(Color.black);
        }
    }//GEN-LAST:event_jplMallaMouseExited

    private void jplMatriculaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jplMatriculaMouseEntered
        if (!isMatriculaClicked) {
            jplMatricula.setBackground(new Color(255,204,0));
            jLabel13.setForeground(Color.black);
        }
    }//GEN-LAST:event_jplMatriculaMouseEntered

    private void jplMatriculaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jplMatriculaMouseExited
        if (!isMatriculaClicked) {
            jplMatricula.setBackground(Color.WHITE);
            jLabel13.setForeground(Color.black);
        }
    }//GEN-LAST:event_jplMatriculaMouseExited

    private void jplPeriodoAcademicoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jplPeriodoAcademicoMouseEntered
        if (!isPeriodoAcademicoClicked) {
            jplPeriodoAcademico.setBackground(new Color(255,204,0));
            jLabel4.setForeground(Color.black);
            jLabel5.setForeground(Color.black);
        }
    }//GEN-LAST:event_jplPeriodoAcademicoMouseEntered

    private void jplPeriodoAcademicoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jplPeriodoAcademicoMouseExited
        if (!isPeriodoAcademicoClicked) {
            jplPeriodoAcademico.setBackground(Color.WHITE);
            jLabel4.setForeground(Color.black);
            jLabel5.setForeground(Color.black);
        }
    }//GEN-LAST:event_jplPeriodoAcademicoMouseExited

    private void jplInicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jplInicioMouseClicked
        isInicioClicked = true;
        jplInicio.setVisible(false);

        JLabel[] labelsBlancos = {jLabel2, jLabel3, jLabel6, jLabel7, jLabel8, jLabel9, jLabel12, jLabel13, jLabel4, jLabel5};
        for (JLabel label : labelsBlancos) {
            label.setForeground(Color.black);
        }

        JPanel[] panelsCianOscuro = {jplDocentes, jplEstudiantes, jplMaterias, jplMalla, jplMatricula, jplPeriodoAcademico};
        for (JPanel panel : panelsCianOscuro) {
            panel.setBackground(Color.WHITE);
        }

        jplInicio.setBackground(new Color(255,204,0));
        jLabel16.setForeground(Color.black);

        jPanel5.removeAll();
        jPanel5.add(panelImage1);
        jPanel5.revalidate();
        jPanel5.repaint();
    }//GEN-LAST:event_jplInicioMouseClicked

    private void jplInicioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jplInicioMouseEntered
        if (!isInicioClicked) {
            jplInicio.setBackground(new Color(255,204,0));
            jLabel16.setForeground(Color.black);
        }
    }//GEN-LAST:event_jplInicioMouseEntered

    private void jplInicioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jplInicioMouseExited
        if (!isInicioClicked) {
            jplInicio.setBackground(Color.WHITE);
            jLabel16.setForeground(Color.black);
        }
    }//GEN-LAST:event_jplInicioMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipalAdministrador1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipalAdministrador1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipalAdministrador1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipalAdministrador1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                String nombre = null;
                String apellidos = null;
                new FrmPrincipalAdministrador1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel jblNombre;
    private javax.swing.JPanel jplDocentes;
    private javax.swing.JPanel jplEstudiantes;
    private javax.swing.JPanel jplInicio;
    private javax.swing.JPanel jplMalla;
    private javax.swing.JPanel jplMaterias;
    private javax.swing.JPanel jplMatricula;
    private javax.swing.JPanel jplPeriodoAcademico;
    private javax.swing.JPanel jplSalir;
    private org.edisoncor.gui.panel.PanelImage panelImage1;
    private org.edisoncor.gui.panel.PanelImage panelImage10;
    private org.edisoncor.gui.panel.PanelImage panelImage11;
    private org.edisoncor.gui.panel.PanelImage panelImage2;
    private org.edisoncor.gui.panel.PanelImage panelImage3;
    private org.edisoncor.gui.panel.PanelImage panelImage4;
    private org.edisoncor.gui.panel.PanelImage panelImage5;
    private org.edisoncor.gui.panel.PanelImage panelImage7;
    private org.edisoncor.gui.panel.PanelImage panelImage8;
    private org.edisoncor.gui.panel.PanelImage panelImage9;
    // End of variables declaration//GEN-END:variables
}
