package vista;


import controladores.DocenteControlador;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import modelo.Docente;

/**
 *
 * @author alexg
 */
public class FrmPrincipalDocenteGrande extends javax.swing.JFrame {

    DocenteControlador dc = new DocenteControlador();
    private Docente docenteLogeado = new Docente();
    public Boolean isInicioClicked = false;
    public Boolean isCreacionClicked = false;
    public Boolean isRevisionClicked = false;
    public Boolean isListadoClicked = false;

    /**
     * Creates new form FrmPrincipalAdministrador
     */
    public FrmPrincipalDocenteGrande(Integer id_docente) {
        initComponents();
        this.setLocationRelativeTo(null);
        cargarImagenes();
        jplInicio.setVisible(false);
        docenteLogeado = dc.buscarDocente(id_docente);
        jblNombre.setText(docenteLogeado.getNombres() + " " + docenteLogeado.getApellidos());
    }

    private String sacarClick(){
        return "Hola";
    }
    // Todo lo siguiente realiza un metodo para verificar el cambio de los atributos
    //public Boolean isInicioClicked = false;
    //public Boolean isCreacionClicked = false;
    //public Boolean isRevisionClicked = false;
    //public Boolean isListadoClicked = false;
    // Y que sean leidos en el Frame de FrmPrincipalDocente
    private static List<ListenerVistas> listeners = new ArrayList<>();

    public interface ListenerVistas {

        void clicksCambio();
    }

    // Método para añadir observadores
    public static void addEstadoChangeListener(ListenerVistas listener) {
        listeners.add(listener);
    }

    // Método para notificar a todos los observadores
    private static void notifyEstadoChange() {
        for (ListenerVistas listener : listeners) {
            listener.clicksCambio();
        }
    }

    // Modificar el setter de isInicioClicked para que notifique a los observadores
    public void setIsInicioClicked(Boolean isInicioClicked) {
        this.isInicioClicked = isInicioClicked;
        notifyEstadoChange();
    }
    public void setIsCreacionClicked(Boolean isCreacionClicked) {
        this.isCreacionClicked = isCreacionClicked;
        notifyEstadoChange();
    }
    public void setIsRevisionClicked(Boolean isRevisionClicked) {
        this.isRevisionClicked = isRevisionClicked;
        notifyEstadoChange();
    }
    public void setIsListadoClicked(Boolean isListadoClicked) {
        this.isListadoClicked = isListadoClicked;
        notifyEstadoChange();
    }

    private void cargarImagenes() {
        ImagenNombre.setIcon(new ImageIcon("src/icono/usuario_prin.png"));
        ImagenInicio.setIcon(new ImageIcon("src/icono/inicio.png"));
        ImagenCreacion.setIcon(new ImageIcon("src/icono/docentes.png"));
        ImagenRevision.setIcon(new ImageIcon("src/icono/estudiantes.png"));
        ImagenListado.setIcon(new ImageIcon("src/icono/materias.png"));
        ImagenSalir.setIcon(new ImageIcon("src/icono/salir.png"));
        ImagenMain.setIcon(new ImageIcon("src/icono/logoEva_1.png"));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jplSalir = new javax.swing.JPanel();
        ImagenSalir = new org.edisoncor.gui.panel.PanelImage();
        jLabel14 = new javax.swing.JLabel();
        jblNombre = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jplCreacion = new javax.swing.JPanel();
        ImagenCreacion = new org.edisoncor.gui.panel.PanelImage();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jplRevision = new javax.swing.JPanel();
        ImagenRevision = new org.edisoncor.gui.panel.PanelImage();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jplListado = new javax.swing.JPanel();
        ImagenListado = new org.edisoncor.gui.panel.PanelImage();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jplInicio = new javax.swing.JPanel();
        ImagenInicio = new org.edisoncor.gui.panel.PanelImage();
        jLabel16 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        ImagenMain = new org.edisoncor.gui.panel.PanelImage();
        ImagenNombre = new org.edisoncor.gui.panel.PanelImage();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));

        jPanel1.setBackground(new java.awt.Color(255, 204, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(255, 255, 255)));

        jplSalir.setBackground(new java.awt.Color(255, 204, 0));
        jplSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jplSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jplSalirMouseClicked(evt);
            }
        });
        jplSalir.setLayout(new java.awt.GridBagLayout());

        javax.swing.GroupLayout ImagenSalirLayout = new javax.swing.GroupLayout(ImagenSalir);
        ImagenSalir.setLayout(ImagenSalirLayout);
        ImagenSalirLayout.setHorizontalGroup(
            ImagenSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );
        ImagenSalirLayout.setVerticalGroup(
            ImagenSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 35;
        gridBagConstraints.ipady = 35;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jplSalir.add(ImagenSalir, gridBagConstraints);

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setText("Cerrar Sesion");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jplSalir.add(jLabel14, gridBagConstraints);

        jblNombre.setFont(new java.awt.Font("Harlow Solid Italic", 1, 18)); // NOI18N
        jblNombre.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jblNombre.setText("Docente");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(jblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 542, Short.MAX_VALUE)
                .addComponent(jplSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jplSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jblNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(0, 6, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(255, 255, 255)));
        jPanel3.setLayout(new java.awt.GridBagLayout());

        jplCreacion.setBackground(new java.awt.Color(255, 255, 255));
        jplCreacion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jplCreacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jplCreacionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jplCreacionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jplCreacionMouseExited(evt);
            }
        });

        javax.swing.GroupLayout ImagenCreacionLayout = new javax.swing.GroupLayout(ImagenCreacion);
        ImagenCreacion.setLayout(ImagenCreacionLayout);
        ImagenCreacionLayout.setHorizontalGroup(
            ImagenCreacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        ImagenCreacionLayout.setVerticalGroup(
            ImagenCreacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Creaciòn de ");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Asignaciones");

        javax.swing.GroupLayout jplCreacionLayout = new javax.swing.GroupLayout(jplCreacion);
        jplCreacion.setLayout(jplCreacionLayout);
        jplCreacionLayout.setHorizontalGroup(
            jplCreacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jplCreacionLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(ImagenCreacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jplCreacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)))
        );
        jplCreacionLayout.setVerticalGroup(
            jplCreacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jplCreacionLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jplCreacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ImagenCreacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jplCreacionLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel3))
                    .addComponent(jLabel2)))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 31;
        gridBagConstraints.ipady = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 0, 0);
        jPanel3.add(jplCreacion, gridBagConstraints);

        jplRevision.setBackground(new java.awt.Color(255, 255, 255));
        jplRevision.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jplRevision.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jplRevisionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jplRevisionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jplRevisionMouseExited(evt);
            }
        });

        javax.swing.GroupLayout ImagenRevisionLayout = new javax.swing.GroupLayout(ImagenRevision);
        ImagenRevision.setLayout(ImagenRevisionLayout);
        ImagenRevisionLayout.setHorizontalGroup(
            ImagenRevisionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        ImagenRevisionLayout.setVerticalGroup(
            ImagenRevisionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Revision de");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Asignaciones");

        javax.swing.GroupLayout jplRevisionLayout = new javax.swing.GroupLayout(jplRevision);
        jplRevision.setLayout(jplRevisionLayout);
        jplRevisionLayout.setHorizontalGroup(
            jplRevisionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jplRevisionLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(ImagenRevision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jplRevisionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)))
        );
        jplRevisionLayout.setVerticalGroup(
            jplRevisionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jplRevisionLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jplRevisionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ImagenRevision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jplRevisionLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel7))
                    .addComponent(jLabel6)))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 31;
        gridBagConstraints.ipady = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 1, 0, 0);
        jPanel3.add(jplRevision, gridBagConstraints);

        jplListado.setBackground(new java.awt.Color(255, 255, 255));
        jplListado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jplListado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jplListadoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jplListadoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jplListadoMouseExited(evt);
            }
        });

        javax.swing.GroupLayout ImagenListadoLayout = new javax.swing.GroupLayout(ImagenListado);
        ImagenListado.setLayout(ImagenListadoLayout);
        ImagenListadoLayout.setHorizontalGroup(
            ImagenListadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        ImagenListadoLayout.setVerticalGroup(
            ImagenListadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Listado de");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Materias");

        javax.swing.GroupLayout jplListadoLayout = new javax.swing.GroupLayout(jplListado);
        jplListado.setLayout(jplListadoLayout);
        jplListadoLayout.setHorizontalGroup(
            jplListadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jplListadoLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(ImagenListado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jplListadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addContainerGap())
        );
        jplListadoLayout.setVerticalGroup(
            jplListadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jplListadoLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jplListadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ImagenListado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addGroup(jplListadoLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel9))))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 44;
        gridBagConstraints.ipady = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(49, 0, 222, 0);
        jPanel3.add(jplListado, gridBagConstraints);

        jplInicio.setBackground(new java.awt.Color(255, 255, 255));
        jplInicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jplInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jplInicioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jplInicioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jplInicioMouseExited(evt);
            }
        });

        javax.swing.GroupLayout ImagenInicioLayout = new javax.swing.GroupLayout(ImagenInicio);
        ImagenInicio.setLayout(ImagenInicioLayout);
        ImagenInicioLayout.setHorizontalGroup(
            ImagenInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        ImagenInicioLayout.setVerticalGroup(
            ImagenInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setText("Inicio");

        javax.swing.GroupLayout jplInicioLayout = new javax.swing.GroupLayout(jplInicio);
        jplInicio.setLayout(jplInicioLayout);
        jplInicioLayout.setHorizontalGroup(
            jplInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jplInicioLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(ImagenInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jplInicioLayout.setVerticalGroup(
            jplInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jplInicioLayout.createSequentialGroup()
                .addGroup(jplInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jplInicioLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel16))
                    .addGroup(jplInicioLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ImagenInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 70;
        gridBagConstraints.ipady = -6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(220, 0, 0, 0);
        jPanel3.add(jplInicio, gridBagConstraints);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setPreferredSize(new java.awt.Dimension(1140, 642));
        jPanel5.setRequestFocusEnabled(false);
        jPanel5.setLayout(new java.awt.GridBagLayout());

        javax.swing.GroupLayout ImagenMainLayout = new javax.swing.GroupLayout(ImagenMain);
        ImagenMain.setLayout(ImagenMainLayout);
        ImagenMainLayout.setHorizontalGroup(
            ImagenMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 595, Short.MAX_VALUE)
        );
        ImagenMainLayout.setVerticalGroup(
            ImagenMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 592, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 595;
        gridBagConstraints.ipady = 592;
        gridBagConstraints.insets = new java.awt.Insets(50, 50, 50, 50);
        jPanel5.add(ImagenMain, gridBagConstraints);

        javax.swing.GroupLayout ImagenNombreLayout = new javax.swing.GroupLayout(ImagenNombre);
        ImagenNombre.setLayout(ImagenNombreLayout);
        ImagenNombreLayout.setHorizontalGroup(
            ImagenNombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 36, Short.MAX_VALUE)
        );
        ImagenNombreLayout.setVerticalGroup(
            ImagenNombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 36, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(225, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(ImagenNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(ImagenNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 642, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jplRevisionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jplRevisionMouseClicked
        setIsRevisionClicked(true);
        isCreacionClicked = false;
        isInicioClicked = false;
        isRevisionClicked = true;
        isListadoClicked = false;
        jplInicio.setVisible(true);

        JLabel[] labelsBlancos = {jLabel2, jLabel3, jLabel6, jLabel7,jLabel8, jLabel9, jLabel16};
        for (JLabel label : labelsBlancos) {
            label.setForeground(Color.black);
        }

        JPanel[] panelsCianOscuro = {jplInicio, jplCreacion, jplListado};
        for (JPanel panel : panelsCianOscuro) {
            panel.setBackground(Color.WHITE);
        }
        jplRevision.setBackground(new Color(255, 204, 0));
        jLabel6.setForeground(Color.black);
        jLabel7.setForeground(Color.black);

        FrmPrincipalDocente vistaPequania = new FrmPrincipalDocente(this, docenteLogeado.getId(), sacarClick());
        JPanel panelDocente = vistaPequania.getjPanel1();
        jPanel5.removeAll();
        jPanel5.add(panelDocente);
        jPanel5.revalidate();
        jPanel5.repaint();
    }//GEN-LAST:event_jplRevisionMouseClicked

    private void jplListadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jplListadoMouseClicked
        setIsListadoClicked(true);
        isCreacionClicked = false;
        isInicioClicked = false;
        isRevisionClicked = false;
        isListadoClicked = true;
        jplInicio.setVisible(true);

        JLabel[] labelsBlancos = {jLabel2, jLabel3, jLabel6, jLabel7,jLabel8, jLabel9, jLabel16};
        for (JLabel label : labelsBlancos) {
            label.setForeground(Color.black);
        }

        JPanel[] panelsCianOscuro = {jplInicio, jplCreacion, jplRevision};
        for (JPanel panel : panelsCianOscuro) {
            panel.setBackground(Color.WHITE);
        }
        jplListado.setBackground(new Color(255, 204, 0));
        jLabel8.setForeground(Color.black);
        jLabel9.setForeground(Color.black);

        FrmPrincipalDocente vistaPequania = new FrmPrincipalDocente(this, docenteLogeado.getId(), sacarClick());
        JPanel panelDocente = vistaPequania.getjPanel1();
        jPanel5.removeAll();
        jPanel5.add(panelDocente);
        jPanel5.revalidate();
        jPanel5.repaint();
    }//GEN-LAST:event_jplListadoMouseClicked

    private void jplSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jplSalirMouseClicked
        new FrmIniciarSesion().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jplSalirMouseClicked

    private void jplRevisionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jplRevisionMouseEntered
        if (!isRevisionClicked) {
            jplRevision.setBackground(new Color(255, 204, 0));
            jLabel6.setForeground(Color.black);
            jLabel7.setForeground(Color.black);
        }
    }//GEN-LAST:event_jplRevisionMouseEntered

    private void jplRevisionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jplRevisionMouseExited
        if (!isRevisionClicked) {
            jplRevision.setBackground(Color.WHITE);
            jLabel6.setForeground(Color.black);
            jLabel7.setForeground(Color.black);
        }
    }//GEN-LAST:event_jplRevisionMouseExited

    private void jplListadoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jplListadoMouseEntered
        if (!isListadoClicked) {
            jplListado.setBackground(new Color(255, 204, 0));
            jLabel8.setForeground(Color.black);
            jLabel9.setForeground(Color.black);
        }
    }//GEN-LAST:event_jplListadoMouseEntered

    private void jplListadoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jplListadoMouseExited
        if (!isListadoClicked) {
            jplListado.setBackground(Color.WHITE);
            jLabel8.setForeground(Color.black);
            jLabel9.setForeground(Color.black);
        }
    }//GEN-LAST:event_jplListadoMouseExited

    private void jplInicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jplInicioMouseClicked
        setIsInicioClicked(true);
        isInicioClicked = true;
        isCreacionClicked = false;
        isRevisionClicked = false;
        isListadoClicked = false;
        
        jplInicio.setVisible(false);

        JLabel[] labelsBlancos = {jLabel2, jLabel3, jLabel6, jLabel7,jLabel8, jLabel9, jLabel16};
        for (JLabel label : labelsBlancos) {
            label.setForeground(Color.black);
        }

        JPanel[] panelsCianOscuro = {jplCreacion, jplRevision, jplListado};
        for (JPanel panel : panelsCianOscuro) {
            panel.setBackground(Color.WHITE);
        }
        jplInicio.setBackground(new Color(255, 204, 0));
        jLabel16.setForeground(Color.black);

        jPanel5.removeAll();
        jPanel5.add(ImagenMain);
        jPanel5.revalidate();
        jPanel5.repaint();
    }//GEN-LAST:event_jplInicioMouseClicked

    private void jplInicioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jplInicioMouseEntered
        if (!isInicioClicked) {
            jplInicio.setBackground(new Color(255, 204, 0));
            jLabel16.setForeground(Color.black);
        } else {

        }
    }//GEN-LAST:event_jplInicioMouseEntered

    private void jplInicioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jplInicioMouseExited
        if (!isInicioClicked) {
            jplInicio.setBackground(Color.WHITE);
            jLabel16.setForeground(Color.black);
        }
    }//GEN-LAST:event_jplInicioMouseExited

    private void jplCreacionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jplCreacionMouseExited
        if (!isCreacionClicked) {
            jplCreacion.setBackground(Color.WHITE);
            jLabel2.setForeground(Color.black);
            jLabel3.setForeground(Color.black);
        }
    }//GEN-LAST:event_jplCreacionMouseExited

    private void jplCreacionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jplCreacionMouseEntered
        if (!isCreacionClicked) {
            jplCreacion.setBackground(new Color(255, 204, 0));
            jLabel2.setForeground(Color.black);
            jLabel3.setForeground(Color.black);
        }
    }//GEN-LAST:event_jplCreacionMouseEntered

    private void jplCreacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jplCreacionMouseClicked
        setIsCreacionClicked(true);
        isCreacionClicked = true;
        isInicioClicked = false;
        isRevisionClicked = false;
        isListadoClicked = false;
        jplInicio.setVisible(true);

        jplInicio.setBackground(Color.white);
        jplRevision.setBackground(Color.white);
        jplListado.setBackground(Color.white);

        JLabel[] labelsBlancos = {jLabel2, jLabel3, jLabel6, jLabel7,jLabel8, jLabel9, jLabel16};
        for (JLabel label : labelsBlancos) {
            label.setForeground(Color.black);
        }

        JPanel[] panelsCianOscuro = {jplInicio, jplRevision, jplListado};
        for (JPanel panel : panelsCianOscuro) {
            panel.setBackground(Color.WHITE);
        }
        jplCreacion.setBackground(new Color(255, 204, 0));
        jLabel2.setForeground(Color.black);
        jLabel3.setForeground(Color.black);

        FrmPrincipalDocente vistaPequania = new FrmPrincipalDocente(this, docenteLogeado.getId(), sacarClick());
        JPanel panelDocente = vistaPequania.getjPanel1();
        jPanel5.removeAll();
        jPanel5.add(panelDocente);
        jPanel5.revalidate();
        jPanel5.repaint();
    }//GEN-LAST:event_jplCreacionMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipalDocenteGrande.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipalDocenteGrande.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipalDocenteGrande.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipalDocenteGrande.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Integer id = null;
                new FrmPrincipalDocenteGrande(id).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.edisoncor.gui.panel.PanelImage ImagenCreacion;
    private org.edisoncor.gui.panel.PanelImage ImagenInicio;
    private org.edisoncor.gui.panel.PanelImage ImagenListado;
    private org.edisoncor.gui.panel.PanelImage ImagenMain;
    private org.edisoncor.gui.panel.PanelImage ImagenNombre;
    private org.edisoncor.gui.panel.PanelImage ImagenRevision;
    private org.edisoncor.gui.panel.PanelImage ImagenSalir;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel jblNombre;
    private javax.swing.JPanel jplCreacion;
    private javax.swing.JPanel jplInicio;
    private javax.swing.JPanel jplListado;
    private javax.swing.JPanel jplRevision;
    private javax.swing.JPanel jplSalir;
    // End of variables declaration//GEN-END:variables
}
